<Project Sdk="Microsoft.NET.Sdk">

	<ItemGroup>
		<FrameworkReference Include="Microsoft.AspNetCore.App" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\Api.Domain\Domain.csproj" />
		<ProjectReference Include="..\Api.Service\Service.csproj" />
		<ProjectReference Include="..\Api.Data\Data.csproj" />
	</ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>

</Project>
